const user = [
  {
    id: 1,
    firstname: "John",
    lastname: "Doe",
    email: "john.doe@example.com",
    contact: "9800000001",
    userType: "lbo",
    userField: "small",
    password: "password123",
  },
  {
    id: 2,
    firstname: "Jane",
    lastname: "Smith",
    email: "jane.smith@example.com",
    contact: "9800000002",
    userType: "consultants",
    userField: "marketing",
    password: "securepass456",
  },
  {
    id: 3,
    firstname: "Rajesh",
    lastname: "Sharma",
    email: "rajesh.sharma@example.com",
    contact: "9800000003",
    userType: "consultants",
    userField: "business",
    password: "rajesh789",
  },
  {
    id: 4,
    firstname: "Emily",
    lastname: "Brown",
    email: "emily.brown@example.com",
    contact: "9800000004",
    userType: "fund",
    userField: "investor fund",
    password: "emilysecure",
  },
  {
    id: 5,
    firstname: "Michael",
    lastname: "Johnson",
    email: "michael.johnson@example.com",
    contact: "9800000005",
    userType: "lbo",
    userField: "micro",
    password: "mikepass123",
  },
  {
    id: 6,
    firstname: "Sarah",
    lastname: "Lee",
    email: "sarah.lee@example.com",
    contact: "9800000006",
    userType: "consultants",
    userField: "legal",
    password: "sarahpass456",
  },
  {
    id: 7,
    firstname: "Amit",
    lastname: "Kumar",
    email: "amit.kumar@example.com",
    contact: "9800000007",
    userType: "consultants",
    userField: "tax",
    password: "amitpassword",
  },
  {
    id: 8,
    firstname: "Lisa",
    lastname: "Taylor",
    email: "lisa.taylor@example.com",
    contact: "9800000008",
    userType: "fund",
    userField: "government grants",
    password: "lisaInvest1",
  },
  {
    id: 9,
    firstname: "David",
    lastname: "Wilson",
    email: "david.wilson@example.com",
    contact: "9800000009",
    userType: "lbo",
    userField: "medium",
    password: "davidpass",
  },
  {
    id: 10,
    firstname: "Nina",
    lastname: "Anderson",
    email: "nina.anderson@example.com",
    contact: "9800000010",
    userType: "consultants",
    userField: "marketing",
    password: "nina123",
  },
  {
    id: 11,
    firstname: "Suraj",
    lastname: "Mishra",
    email: "suraj.mishra@example.com",
    contact: "9800000011",
    userType: "consultants",
    userField: "business",
    password: "surajMishra",
  },
  {
    id: 12,
    firstname: "Priya",
    lastname: "Choudhary",
    email: "priya.choudhary@example.com",
    contact: "9800000012",
    userType: "fund",
    userField: "business development loans",
    password: "priyaInvest",
  },
  {
    id: 13,
    firstname: "Robert",
    lastname: "Jones",
    email: "robert.jones@example.com",
    contact: "9800000013",
    userType: "lbo",
    userField: "small",
    password: "robertsecure",
  },
  {
    id: 14,
    firstname: "Amelia",
    lastname: "Davis",
    email: "amelia.davis@example.com",
    contact: "9800000014",
    userType: "consultants",
    userField: "legal",
    password: "amelia567",
  },
  {
    id: 15,
    firstname: "Krishna",
    lastname: "Poudel",
    email: "krishna.poudel@example.com",
    contact: "9800000015",
    userType: "consultants",
    userField: "tax",
    password: "krishna123",
  },
  {
    id: 16,
    firstname: "Anjali",
    lastname: "Joshi",
    email: "anjali.joshi@example.com",
    contact: "9800000016",
    userType: "fund",
    userField: "investor fund",
    password: "anjaliPass",
  },
  {
    id: 17,
    firstname: "Ethan",
    lastname: "White",
    email: "ethan.white@example.com",
    contact: "9800000017",
    userType: "lbo",
    userField: "micro",
    password: "ethanLocal",
  },
  {
    id: 18,
    firstname: "Sophia",
    lastname: "Martinez",
    email: "sophia.martinez@example.com",
    contact: "9800000018",
    userType: "consultants",
    userField: "marketing",
    password: "sophiaSecure",
  },
  {
    id: 19,
    firstname: "Sanjay",
    lastname: "Bhandari",
    email: "sanjay.bhandari@example.com",
    contact: "9800000019",
    userType: "consultants",
    userField: "business",
    password: "sanjayPass",
  },
  {
    id: 20,
    firstname: "Laxmi",
    lastname: "Thapa",
    email: "laxmi.thapa@example.com",
    contact: "9800000020",
    userType: "fund",
    userField: "government grants",
    password: "laxmiInvest",
  },
  {
    id: 21,
    firstname: "Harish",
    lastname: "Gupta",
    email: "harish.gupta@example.com",
    contact: "9800000021",
    userType: "lbo",
    userField: "small",
    password: "harishPass123",
  },
  {
    id: 22,
    firstname: "Meena",
    lastname: "Shrestha",
    email: "meena.shrestha@example.com",
    contact: "9800000022",
    userType: "consultants",
    userField: "marketing",
    password: "meenaSecure",
  },
  {
    id: 23,
    firstname: "Ramesh",
    lastname: "Adhikari",
    email: "ramesh.adhikari@example.com",
    contact: "9800000023",
    userType: "consultants",
    userField: "business",
    password: "rameshConsult",
  },
  {
    id: 24,
    firstname: "Sita",
    lastname: "Rai",
    email: "sita.rai@example.com",
    contact: "9800000024",
    userType: "fund",
    userField: "investor fund",
    password: "sitaFund",
  },
  {
    id: 25,
    firstname: "Ganesh",
    lastname: "Tamang",
    email: "ganesh.tamang@example.com",
    contact: "9800000025",
    userType: "lbo",
    userField: "micro",
    password: "ganeshMicro",
  },
  {
    id: 26,
    firstname: "Aarati",
    lastname: "Karki",
    email: "aarati.karki@example.com",
    contact: "9800000026",
    userType: "consultants",
    userField: "legal",
    password: "aaratiLegal",
  },
  {
    id: 27,
    firstname: "Kripa",
    lastname: "Pandey",
    email: "kripa.pandey@example.com",
    contact: "9800000027",
    userType: "consultants",
    userField: "tax",
    password: "kripaTax",
  },
  {
    id: 28,
    firstname: "Mohan",
    lastname: "Thapa",
    email: "mohan.thapa@example.com",
    contact: "9800000028",
    userType: "fund",
    userField: "government grants",
    password: "mohanFund",
  },
  {
    id: 29,
    firstname: "Anita",
    lastname: "Shah",
    email: "anita.shah@example.com",
    contact: "9800000029",
    userType: "lbo",
    userField: "medium",
    password: "anitaMedium",
  },
  {
    id: 30,
    firstname: "Raju",
    lastname: "Bista",
    email: "raju.bista@example.com",
    contact: "9800000030",
    userType: "consultants",
    userField: "marketing",
    password: "rajuMarketing",
  },
  {
    id: 31,
    firstname: "Kamal",
    lastname: "Basnet",
    email: "kamal.basnet@example.com",
    contact: "9800000031",
    userType: "consultants",
    userField: "business",
    password: "kamalBusiness",
  },
  {
    id: 32,
    firstname: "Sunita",
    lastname: "Lama",
    email: "sunita.lama@example.com",
    contact: "9800000032",
    userType: "fund",
    userField: "business development loans",
    password: "sunitaFund",
  },
  {
    id: 33,
    firstname: "Prakash",
    lastname: "Rana",
    email: "prakash.rana@example.com",
    contact: "9800000033",
    userType: "lbo",
    userField: "small",
    password: "prakashSmall",
  },
  {
    id: 34,
    firstname: "Bina",
    lastname: "KC",
    email: "bina.kc@example.com",
    contact: "9800000034",
    userType: "consultants",
    userField: "legal",
    password: "binaLegal",
  },
  {
    id: 35,
    firstname: "Manish",
    lastname: "Joshi",
    email: "manish.joshi@example.com",
    contact: "9800000035",
    userType: "consultants",
    userField: "tax",
    password: "manishTax",
  },
  {
    id: 36,
    firstname: "Rita",
    lastname: "Gurung",
    email: "rita.gurung@example.com",
    contact: "9800000036",
    userType: "fund",
    userField: "investor fund",
    password: "ritaFund",
  },
  {
    id: 37,
    firstname: "Bijay",
    lastname: "Khadka",
    email: "bijay.khadka@example.com",
    contact: "9800000037",
    userType: "lbo",
    userField: "micro",
    password: "bijayMicro",
  },
  {
    id: 38,
    firstname: "Preeti",
    lastname: "Bhattarai",
    email: "preeti.bhattarai@example.com",
    contact: "9800000038",
    userType: "consultants",
    userField: "marketing",
    password: "preetiMarketing",
  },
  {
    id: 39,
    firstname: "Sujan",
    lastname: "Maharjan",
    email: "sujan.maharjan@example.com",
    contact: "9800000039",
    userType: "consultants",
    userField: "business",
    password: "sujanBusiness",
  },
  {
    id: 40,
    firstname: "Rekha",
    lastname: "Rai",
    email: "rekha.rai@example.com",
    contact: "9800000040",
    userType: "fund",
    userField: "government grants",
    password: "rekhaFund",
  },
  {
      id: 41,
      firstname: "Anish",
      lastname: "Bhattrai",
      email: "Anish.Bhattrai_22@eemc.edu.np",
      contact: "9841032589",
      userType: "lbo",
      userField: "medium",
      password: "12345678",
    },
];

export { user };
